### ISSUE TITLE
Auto enable option

### ISSUE THREAD

**Issue by iIInfernoDashIi** [Watkin81/UnixSync#1]
Would like to suggest new mod setting, "Auto enable", "Auto detect" or something like that.
While this option enabled, mod functionality will automatically toggles on for any level that has `UnixSync` in it's description.

**Comment by Watkin81** [comment]
This functionality has been added in v1.3.0, thank you for the suggestion. Creators can check a box in the editor that will enable the sync for those who enter the level, and it won't work on other levels making the mod perfectly safe to use and much more simple for everyone involved.

**Comment by Watkin81** [comment]
This functionality has been added in v1.3.0, thank you for the suggestion. Creators can check a box in the editor that will enable the sync for those who enter the level, and it won't work on other levels making the mod perfectly safe to use and much more simple for everyone involved.
